[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "fastapi>=0.115.13",
    "playwright>=1.52.0",
    "python-multipart>=0.0.20",
    "uvicorn>=0.34.3",
    "websockets>=15.0.1",
]
